### ISSUE TITLE
Inability to run `serve` locally

### ISSUE THREAD

**Issue by doismellburning** [PyconUK/2016.pyconuk.org#282]
```
$ DEBUG=True python manage.py serve
<snip>

System check identified no issues (0 silenced).
September 24, 2016 - 14:19:25
Django version 1.9.7, using settings 'pyconuk.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/kristian/git/2016.pyconuk.org/.env/lib/python3.5/site-packages/compressor/base.py", line 260, in precompile
    mod = import_module(mod_name)
  File "/Users/kristian/git/2016.pyconuk.org/.env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'lessc {infile} {outfile}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

<snip>

compressor.exceptions.FilterError: /bin/sh: lessc: command not found

[24/Sep/2016 14:19:25] "GET / HTTP/1.1" 500 235735
```

From the README:

> This site uses django-amber_. To install django-amber and other dependencies, run `pip install -r requirements.txt`.  django-amber is only known to work with Python 3.5.

I did this, cf. the following:

```
$ pip freeze
/opt/badger/2016.pyconuk.org/.env/lib/python3.5/distutils/__init__.py:4: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Django==1.9.7
django-amber==0.5.0
django-appconf==1.0.2
django-compressor==2.1
django-markdown-deux==1.0.5
http-crawler==0.1.2
lxml==3.6.0
markdown2==2.3.1
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.11
rcssmin==1.0.6
requests==2.10.0
rjsmin==1.0.12
six==1.10.0
tinycss2==0.5
vobject==0.9.3
webencodings==0.5
```

Is the README true and total and the error message is misleading and lack of `lessc` is a noncritical failure, or is there a missing dependency declaration?

**Comment by doismellburning** [comment]
I should have read the `.travis.yml` first; there is a missing dependency declaration
